export {
    COUNT_FEEDBACKS_TO_SHOW,
    MIN_LENGTH_PASSWORD,
    TOKEN_AUTH_LOCALSTORAGE,
    MAX_SIZE_PHOTO_USER_MB,
    DEFAULT_TRAINING_NAME_VARIANT,
    ERROR_MESSAGES,
} from './common';

export { ROUTES_LINKS } from './navigation';

export { DATE_FORMAT, DATE_FORMAT_TO_VIEW, DATE_SHORT_FORMAT_TO_VIEW } from './date';

export { SERVICE_API_URL, REPEAT_FEEDBACKS_REQUEST, STATUS_CODES, API_TAGS } from './service';

export { MODALS_STYLE } from './modals';

export { MEDIA_SERVER_URL, MEDIA_LOADING_STATUS, MAX_WIDTH_FOR_MOBILE_PX } from './media';

export {
    TRAININGS_IDS,
    NAVIGATION_IDS,
    LOADER_ID,
    FEEDBACKS_IDS,
    USER_IDS,
    PROFILE_IDS,
    SETTINGS_IDS,
} from './test-info';
